set(_CATKIN_CURRENT_PACKAGE "dt-joystick-demo")
set(dt-joystick-demo_VERSION "0.0.1")
set(dt-joystick-demo_MAINTAINER "Nicolas_Bosteels <NICOLASBOSTEELS0@GMAIL.COM>")
set(dt-joystick-demo_PACKAGE_FORMAT "1")
set(dt-joystick-demo_BUILD_DEPENDS )
set(dt-joystick-demo_BUILD_EXPORT_DEPENDS )
set(dt-joystick-demo_BUILDTOOL_DEPENDS "catkin")
set(dt-joystick-demo_BUILDTOOL_EXPORT_DEPENDS )
set(dt-joystick-demo_EXEC_DEPENDS )
set(dt-joystick-demo_RUN_DEPENDS )
set(dt-joystick-demo_TEST_DEPENDS )
set(dt-joystick-demo_DOC_DEPENDS )
set(dt-joystick-demo_URL_WEBSITE "")
set(dt-joystick-demo_URL_BUGTRACKER "")
set(dt-joystick-demo_URL_REPOSITORY "")
set(dt-joystick-demo_DEPRECATED "")