set(_CATKIN_CURRENT_PACKAGE "dt_joystick_demo_msgs")
set(dt_joystick_demo_msgs_VERSION "0.0.0")
set(dt_joystick_demo_msgs_MAINTAINER "vsuser <vsuser@todo.todo>")
set(dt_joystick_demo_msgs_PACKAGE_FORMAT "2")
set(dt_joystick_demo_msgs_BUILD_DEPENDS "message_generation" "rospy")
set(dt_joystick_demo_msgs_BUILD_EXPORT_DEPENDS "rospy")
set(dt_joystick_demo_msgs_BUILDTOOL_DEPENDS "catkin")
set(dt_joystick_demo_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(dt_joystick_demo_msgs_EXEC_DEPENDS "message_runtime" "rospy")
set(dt_joystick_demo_msgs_RUN_DEPENDS "message_runtime" "rospy")
set(dt_joystick_demo_msgs_TEST_DEPENDS )
set(dt_joystick_demo_msgs_DOC_DEPENDS )
set(dt_joystick_demo_msgs_URL_WEBSITE "")
set(dt_joystick_demo_msgs_URL_BUGTRACKER "")
set(dt_joystick_demo_msgs_URL_REPOSITORY "")
set(dt_joystick_demo_msgs_DEPRECATED "")